ALTER TABLE survey_form
DROP COLUMN form_type,
    ADD COLUMN title VARCHAR(255) NOT NULL COMMENT '설문 제목',
    ADD COLUMN due_at DATETIME NOT NULL COMMENT '응답 마감 일시',
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'DRAFT'
        COMMENT '설문 상태',
    ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        COMMENT '생성 일시',
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
                    ADD CONSTRAINT UQ_SURVEY_FORM_GOOGLE_FORM_ID
                    UNIQUE (google_form_id);